### PR TITLE
Add support for PHP 8

### PR DESCRIPTION
**Pull request by mnapoli**

### CODE REVIEW

**Comment by rdohms** [comment]
@mnapoli can we either add PHP8 to the matrix in Travis, or migrate to GHA and then add that?

**Comment by mnapoli** [comment]
Oh that makes complete sense yes! I don't have the time unfortunately right now, but I'll try to contribute as soon as I can.

**Comment by rdohms** [comment]
Looks like It covered by the other PRs, I'll rebase and merge later.

**Comment by mnapoli** [comment]
Thanks!

**Pull request merged**
